## 중간고사 대체 과제
-  [OpenML](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_openml.html) is a public repository for machine learning datasets and experiments
- 'recall_macro"를 최대화 하는 모델을 개발하고 제시하라
- mage.ai ETL 파이프라인으로 구성하여 제시하라

In [ ]:
from sklearn.datasets import fetch_openml
X, y = fetch_openml("Bank_marketing_data_set_UCI", return_X_y= True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [ ]:
X.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome  
0  unknown    5   may       261         1     -1         0  unknown  
1  unknown    5   may       151         1     -1         0  unknown  
2  unknown    5   may        76         1     -1         0  unknown  
3  unknown    5   may        92         1     -1         0  unknown  
4  unknown    5   may       198         1     -1         0  unknown

In [ ]:
y[:5]

0    no
1    no
2    no
3    no
4    no
Name: y, dtype: object

In [ ]:
y.value_counts(normalize=True).round(2)

y
no     0.88
yes    0.12
Name: proportion, dtype: float64

## **Split data to learn**

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(1,21).reshape((10, 2)), range(1, 11)
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [11]:
list(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33) #random_state=42)
X_train

array([[13, 14],
       [ 3,  4],
       [ 1,  2],
       [17, 18],
       [11, 12],
       [ 5,  6]])

In [17]:
y_train

[8, 9, 3, 7, 6, 4]

In [14]:
X_test

array([[17, 18],
       [ 3,  4],
       [11, 12],
       [ 1,  2]])

In [15]:
y_test

[9, 2, 6, 1]